apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: cassandra
  namespace: default
spec:
  serviceAccountName: cluster-admin-sa
  fetch:
  - git:
      url: https://github.com/jerrinsg/kubernetes-examples
      ref: origin/master
      subPath: cassandra
  template:
  - ytt:
      ignoreUnknownComments: true
  deploy:
  - kapp: {}