name: 'Test Sieve GitHub action'

on:
  workflow_dispatch:
  
jobs:
  run-sieve:
    runs-on: macos-latest 
    steps:
      - uses: jerrinsg/sieve-action@HEAD
        with:
          controller_config: https://raw.githubusercontent.com/jerrinsg/sieve-action-test/main/config.json
          controller_build: https://raw.githubusercontent.com/jerrinsg/sieve-action-test/main/build.sh
          controller_dockerfile: https://raw.githubusercontent.com/jerrinsg/sieve-action-test/main/Dockerfile
          controller_deployment: https://raw.githubusercontent.com/jerrinsg/sieve-action-test/main/release.yml
          controller_script: https://raw.githubusercontent.com/jerrinsg/sieve-action-test/main/deploy.sh
          workload_name: scale-up-down
          test_file: https://raw.githubusercontent.com/jerrinsg/sieve-action-test/main/test.py
          test_prereqs: https://raw.githubusercontent.com/jerrinsg/sieve-action-test/main/prereqs.sh
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
