name: 'Test Sieve GitHub action (kapp-controller) on Linux (cassandra deployment)'

on:
  workflow_dispatch:

jobs:
  run-sieve:
    uses: jerrinsg/sieve/.github/workflows/run-sieve.yml@main
    with:
      platform-os: ubuntu-latest
      controller-name: kapp-controller
      github-repo: https://github.com/jerrinsg/sieve-action-test.git
      subdirectory: kapp-controller
      workload_name: scale-up-down
    secrets:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}