name: 'Test Sieve GitHub action with cassandra-operator on Linux'

on:
  workflow_dispatch:

jobs:
  run-sieve:
    uses: jerrinsg/sieve/.github/workflows/run-sieve.yml@main
    with:
      platform-os: ubuntu-latest
      controller-name: cassandra-operator
      github-repo: https://github.com/jerrinsg/sieve-action-test.git
      subdirectory: cassandra-operator
      workload_name: recreate
    secrets:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
