name: 'Test Sieve GitHub action on macOS'

on:
  workflow_dispatch:
  
jobs:
  run-sieve:
    uses: jerrinsg/sieve/.github/workflows/run-sieve.yml@main
    with:
      platform-os: macos-latest
      controller-name: kapp-controller
      github-repo: https://github.com/jerrinsg/sieve-action-test.git
      subdirectory: kapp-controller-simple
      workload_name: create
    secrets:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
